### ISSUE TITLE
Error in ExtractOccsFromWikipedia - java.util.NoSuchElementException: key not found: 828

### ISSUE THREAD

**Issue by stefanoabbate** [dbpedia-spotlight/dbpedia-spotlight#234]
Dear all:

Continuing with the indexing phase, using the new configuration of DBpedia Spotlight, I am facing a problem after a while the following commad has been executed: `mvn scala:run -Dlauncher=ExtractOccsFromWikipedia "-DjavaOpts.Xmx=$JAVA_XMX" "-DaddArgs=$INDEX_CONFIG_FILE|$DBPEDIA_WORKSPACE/data/output/it/occs.tsv"`

There is a `java.util.NoSuchElementException: key not found: 828` problem. I have already checked the problem on the Internet and what I have found is [this](http://www.mail-archive.com/dbpedia-developers@lists.sourceforge.net/msg00032.html).

The output is:

`INFO 2013-10-04 10:15:41,855 main [FileOccurrenceSource$] -   saved 21000000 occurrences
 INFO 2013-10-04 10:17:03,968 main [FileOccurrenceSource$] -   saved 21100000 occurrences
 INFO 2013-10-04 10:17:47,293 main [AllOccurrenceSource$AllOccurrenceSource] - Processed 1500000 Wikipedia definition pages (average 16.74 links per page)
 INFO 2013-10-04 10:18:35,467 main [FileOccurrenceSource$] -   saved 21200000 occurrences
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.util.NoSuchElementException: key not found: 828
	at scala.collection.MapLike$class.default(MapLike.scala:225)
	at scala.collection.immutable.HashMap.default(HashMap.scala:38)
	at scala.collection.MapLike$class.apply(MapLike.scala:135)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:38)
	at org.dbpedia.extraction.sources.WikipediaDumpParser.readPage(WikipediaDumpParser.java:218)
	at org.dbpedia.extraction.sources.WikipediaDumpParser.readPages(WikipediaDumpParser.java:179)
	at org.dbpedia.extraction.sources.WikipediaDumpParser.readDump(WikipediaDumpParser.java:137)
	at org.dbpedia.extraction.sources.WikipediaDumpParser.run(WikipediaDumpParser.java:108)
	at org.dbpedia.extraction.sources.XMLReaderSource.foreach(XMLSource.scala:57)
	at org.dbpedia.spotlight.io.AllOccurrenceSource$AllOccurrenceSource.foreach(AllOccurrenceSource.scala:78)
	at org.dbpedia.spotlight.filter.Filter$FilteredOccs.foreach(Filter.scala:58)
	at org.dbpedia.spotlight.filter.Filter$FilteredOccs.foreach(Filter.scala:58)
	at org.dbpedia.spotlight.filter.Filter$FilteredOccs.foreach(Filter.scala:58)
	at org.dbpedia.spotlight.io.FileOccurrenceSource$.writeToFile(FileOccurrenceSource.scala:55)
	at org.dbpedia.spotlight.lucene.index.ExtractOccsFromWikipedia$.main(ExtractOccsFromWikipedia.scala:80)
	at org.dbpedia.spotlight.lucene.index.ExtractOccsFromWikipedia.main(ExtractOccsFromWikipedia.scala)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:20:19.020s
[INFO] Finished at: Fri Oct 04 10:18:51 CEST 2013
[INFO] Final Memory: 15M/153M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:run (default-cli) on project index: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Any hints? In the [Italian namespace](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/wikiparser/impl/wikipedia/Namespaces.scala) there is the key 828 (Module/Modulo) but I am not sure it is in included in the actual version of DBpedia Spotlight.

Thanks,

Stefano

**Comment by sandroacoelho** [comment]
Hi @stefanoabbate 


This issue was solved and I have success to create the models in the following languages: german , greek , english, spanish, french , italian, dutch, polish, portuguese and russian.

You have now two options ready to use :

For the statistical backend, please follow [these instructions](https://github.com/dbpedia-spotlight/model-quickstarter)

For Lucene, please follow [these] (https://github.com/sandroacoelho/lucene-quickstarter)

Best,

**Comment by stefanoabbate** [comment]
Thank you!
