### ISSUE TITLE
Creating an index for German DBpedia 2014

### ISSUE THREAD

**Issue by RicardoUsbeck** [dbpedia-spotlight/dbpedia-spotlight#321]
Dear all, 

I am new to scala and wanted to setup a new index for the new DBpedia since I did not find any precompiled version and ended up in the error below.

Here is what I did: 

``` shell
git clone https://github.com/dbpedia-spotlight/model-quickstarter.git
cd model-quickstarter/
./prepare.sh
```

!set inside indexdb.sh local_mode="true"

!set download directory

``` shell
cd $WDIR
if [ ! -f "redirects.nt" ]; then
  curl -# http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/redirects_de.nt.bz2 | bzcat > redirects.nt
  curl -# http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/disambiguations_de.nt.bz2 | bzcat > disambiguations.nt
  curl -# http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/instance_types_de.nt.bz2 | bzcat > instance_types.nt
fi
```

``` shell
./index_db.sh -o de wdir de_DE de/stopwords.list German  models/de
```

`````` shell
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/com/aliasi/lingpipe/4.1.0/lingpipe-4.1.0.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/opennlp/maxent/3.0.0/maxent-3.0.0.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/weka/kea-goss-weka/5.0-SNAPSHOT/kea-goss-weka-5.0-SNAPSHOT.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/edu/umd/cloud9/SNAPSHOT/cloud9-SNAPSHOT.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/org/semanticweb/yars/nxparser/1.1/nxparser-1.1.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/weka/kea-goss-weka/5.0-SNAPSHOT/kea-goss-weka-5.0-SNAPSHOT.jar
Downloaded: http://opennlp.sourceforge.net/maven2/weka/kea-goss-weka/5.0-SNAPSHOT/kea-goss-weka-5.0-SNAPSHOT.jar (2 KB at 3.2 KB/sec)
Downloading: http://opennlp.sourceforge.net/maven2/scala/ahocorasick/spotter-aho/0.1/spotter-aho-0.1.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/com/aliasi/lingpipe/4.1.0/lingpipe-4.1.0.jar
Downloaded: http://opennlp.sourceforge.net/maven2/com/aliasi/lingpipe/4.1.0/lingpipe-4.1.0.jar (2 KB at 3.2 KB/sec)
Downloading: http://opennlp.sourceforge.net/maven2/com/typesafe/akka/akka-actor/2.0.5/akka-actor-2.0.5.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/opennlp/maxent/3.0.0/maxent-3.0.0.jar
Downloaded: http://opennlp.sourceforge.net/maven2/opennlp/maxent/3.0.0/maxent-3.0.0.jar (2 KB at 3.2 KB/sec)
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/edu/umd/cloud9/SNAPSHOT/cloud9-SNAPSHOT.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/org/semanticweb/yars/nxparser/1.1/nxparser-1.1.jar
Downloaded: http://opennlp.sourceforge.net/maven2/edu/umd/cloud9/SNAPSHOT/cloud9-SNAPSHOT.jar (2 KB at 3.1 KB/sec)
Downloaded: http://opennlp.sourceforge.net/maven2/org/semanticweb/yars/nxparser/1.1/nxparser-1.1.jar (2 KB at 3.1 KB/sec)
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/scala/ahocorasick/spotter-aho/0.1/spotter-aho-0.1.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/com/typesafe/akka/akka-actor/2.0.5/akka-actor-2.0.5.jar
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/scala/ahocorasick/spotter-aho/0.1/spotter-aho-0.1.jar
Downloaded: http://opennlp.sourceforge.net/maven2/scala/ahocorasick/spotter-aho/0.1/spotter-aho-0.1.jar (2 KB at 4.1 KB/sec)
[WARNING] Checksum validation failed, expected <html> but is 37d922b558db37710887551abcee8921d837a68d for http://opennlp.sourceforge.net/maven2/com/typesafe/akka/akka-actor/2.0.5/akka-actor-2.0.5.jar
Downloaded: http://opennlp.sourceforge.net/maven2/com/typesafe/akka/akka-actor/2.0.5/akka-actor-2.0.5.jar (2 KB at 4.1 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ core ---
[INFO] Deleting file set: /root/model-quickstarter/wdir/dbpedia-spotlight/core/target (included: [**], excluded: [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven-3) @ core ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java-newer-6) @ core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:add-source (scala-compile-first) @ core ---
[INFO] Add Source directory: /root/model-quickstarter/wdir/dbpedia-spotlight/core/src/main/scala
[INFO] Add Test Source directory: /root/model-quickstarter/wdir/dbpedia-spotlight/core/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:compile (scala-compile-first) @ core ---
[WARNING] Invalid POM for org.dbpedia.extraction:core:jar:3.8, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.semanticweb.yars:nxparser:jar:1.1, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for com.aliasi:lingpipe:jar:4.1.0, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for edu.umd:cloud9:jar:SNAPSHOT, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for weka:kea-goss-weka:jar:5.0-SNAPSHOT, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for weka:weka:jar:3.7.3, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for opennlp:maxent:jar:3.0.0, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for jdbm:jdbm:jar:3.0-SNAPSHOT, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for scala.ahocorasick:spotter-aho:jar:0.1, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for com.typesafe.akka:akka-actor:jar:2.0.5, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING]  Expected all dependencies to require Scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  org.scala-lang:scalap:2.9.2 requires scala version: 2.9.2
[WARNING]  org.scalatest:scalatest_2.9.2:2.0.M4 requires scala version: 2.9.2
[WARNING]  org.scalaz:scalaz-core_2.9.2:6.0.4 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-math_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-process_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-learn_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  com.codecommit:anti-xml_2.9.1:0.3 requires scala version: 2.9.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] /root/model-quickstarter/wdir/dbpedia-spotlight/core/src/main/java:-1: info: compiling
[INFO] /root/model-quickstarter/wdir/dbpedia-spotlight/core/src/main/scala:-1: info: compiling
[INFO] Compiling 232 source files to /root/model-quickstarter/wdir/dbpedia-spotlight/core/target/classes at 1412174489636
[ERROR] error: error while loading <root>, error in opening zip file
[ERROR] error: scala.tools.nsc.MissingRequirementError: object scala not found.
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModuleOrClass(Definitions.scala:655)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModule(Definitions.scala:605)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackage(Definitions.scala:145)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackageClass(Definitions.scala:146)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.AnyClass(Definitions.scala:176)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:814)
[INFO]  at scala.tools.nsc.Global$Run.<init>(Global.scala:697)
[INFO]  at scala.tools.nsc.Main$.process(Main.scala:105)
[INFO]  at scala.tools.nsc.Main$.main(Main.scala:123)
[INFO]  at scala.tools.nsc.Main.main(Main.scala)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO]  at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] 
[ERROR] error: fatal error: object scala not found.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DBpedia Spotlight annotation framework (parent POM)  SUCCESS [1.485s]
[INFO] DBpedia Spotlight Core ............................ FAILURE [1:19.022s]
[INFO] DBpedia Spotlight RESTful API ..................... SKIPPED
[INFO] DBpedia Spotlight Indexing ........................ SKIPPED
[INFO] DBpedia Spotlight Evaluation ...................... SKIPPED
[INFO] DBpedia Spotlight UIMA Integration ................ SKIPPED
[INFO] DBpedia Spotlight Distribution Packaging .......... SKIPPED
[INFO] DBpedia Spotlight RESTful TOMCAT .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:20.992s
[INFO] Finished at: Wed Oct 01 14:41:30 UTC 2014
[INFO] Final Memory: 14M/503M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:compile (scala-compile-first) on project core: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core
Updating PigNLProc...
HEAD is now at 37f70c1 Merge pull request #13 from sandroacoelho/v0.7
Already up-to-date.
[ERROR] Failed to execute goal on project pignlproc: Could not resolve dependencies for project pignlproc:pignlproc:jar:0.1.0-SNAPSHOT: Could not find artifact org.dbpedia.spotlight:core:jar:0.7 in info-bliki-repository (http://gwtwiki.googlecode.com/svn/maven-repository/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```shell
``````

**Comment by tgalery** [comment]
Hi @RicardoUsbeck I m trying to generate the model for english, and I was having a similar problem as you. I suspect that you might be using hadoop 2+ and it's something related to that. The main problem is that the nerd commons macro and soma java files need updating. Michael updated this on his branch and it worked https://github.com/michellemay/pignlproc . However, I tried to redo his steps and the job got stuck in the EMR cluster. 

The whole model extraction thing is a bit confusing cause code is scattered across 3 repos, the model-quickstarter, pignlproc and dbpedia-spotlight itself. Plus the helper scripts that download maven, pig, and set env vars sometimes don't work that well, different architectures, so on and so forth. I've tried to unify things into a single place https://github.com/tgalery/pignlproc/tree/feature/repo-unification and striped out all the code that downloads boiller plate.

I managed to run locally on Danish and it worked fined. I'm running this atm on a R3.xlarge (local mode ) to generate the new english model and it seems to be working so far (pig 0.14.0, hadoop 2.6.0). If you want to pull that branch, give a go, and talk about it, that would be great. Differently from @michellemay I'm not using the scala 2.11 stuff.

**Comment by RicardoUsbeck** [comment]
Hi Thiago,

I am running it without Hadoop, only locally. But I gave this task to a colleague and I am not sure how far he is. He will report soon. @dcherix

**Comment by rschwab68** [comment]
Hi @RicardoUsbeck ,
I have just finished to create a model for german in local mode.

**Comment by RicardoUsbeck** [comment]
Hi @rschwab68 ,

Thank you for making the effort. How did you make it? Or more important, can you provide the model somehow?

Greetings,
Ricardo

**Comment by rschwab68** [comment]
hi @RicardoUsbeck ,
I have done it according to the script applying some changes when problems have arisen.
nothing special.
I still have not checked and tested the generated models.
I have promised to joachim that I will document how i have done it.
but give me some time.

**Comment by UweHartwig** [comment]
hi @rschwab68 ,
related to your wiki entry (https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Run-Apache-Pig-in-local-mode), where exactly (line?) is one supposed to add those lines in mentioned two .pig-files?

**Comment by UweHartwig** [comment]
Dear all,
in the current index_db.sh the Apache PIG gets build two times, once from the dbpedia-spotlight github repo and the old 0.10.-version in local_mode. I cant figure out which version is really used in local_mode. It seems to me that only the PIGNLPROC_JAR is used in both flavours which points to the version from the github repo. Any ideas?
