### ISSUE TITLE
Running pignlproc under Amazon EMR

### ISSUE THREAD

**Issue by michellemay** [dbpedia-spotlight/dbpedia-spotlight#329]
Hi, is anybody tried to launch model trainer under amazon elastic map reduce service?
Any automated script for that?

Right now, I see many hurdles:
1) Amazon Pig versions are 0.9.2, 0.11.1 and 12.0 and Hadoop 2.4, 2.2, 1.0.3, 0.20.205
2) S3 paths
3) Automation using ruby, aws CLI?
4) Working on compressed bz2 wiki dumps

1) Pig/Hadoop versions:
Each of theses versions of Pig might causes compilation errors. We need to adapt pom.xml in order to target specific hadoop (hadoop-common and hadoop-mapreduce-client-core for 2.2 and later)

2) S3 output paths.. I got failures running names_and_entities.pig step.  It tries to load temporary surface forms from what seems to an invalid folder in S3.  This is probably due to a file-open in the ./ current folder which does not exist in S3.

3) Automation.  
Since the training process requires some steps to be run after last pig job, we could use an EC2 with necessarily tools (JDK, Maven, Ruby, s3cmd).

4) It might not be up-to-date, but I saw somewhere on theses pages that pignlproc should have uncompressed wiki dumps.  What would be needed in order to work directly with compressed dumps (Amazon should do most of the job here according to their documentation)

All that said, I'm more than willing to spend some time and amazon money on this granted some support of the project owner.

Michel

**Comment by tgalery** [comment]
@michellemay I was starting to look into this again. 14 days after your last message, spark 1.2 was released. It seems that it does support scala 2.11 (beta-ish) https://spark.apache.org/releases/spark-release-1-2-0.html, but it might worth a go. I might try to redo your steps tomorrow. If you sucessfully generated a new model, would it by any chance be publicaly available ?

**Comment by michellemay** [comment]
@tgalery I've not done any more work on this aspect lately.  However, I've took considerable time experimenting with Spark (in standalone mode on my 32 cores machine) and I'm quite pleased to see how well it performs.  In my opinion,  dbpedia spotlight models could be generated significantly faster with it.  And Spark seems to have a great traction as we speak.

**Comment by tgalery** [comment]
Tried to compile spark 1.2 with scala 2.11 support and no dice :-1:

**Comment by michellemay** [comment]
I think we should focus on 2.10.  Too many missing components in 2.11.

**Comment by tgalery** [comment]
Hi @michellemay I'm trying to reproduce your steps and I had many problems with setting up the dependencies. Here are some issues I found:
(i) maven could not be downloaded from the canadian mirror that's hardcoded (maybe using curl to a base url and follow the ridirects)
(ii) maven home might set for one bash session and is unset when running the `index_db` script. (maybe variables should be set at the environment level)
(iii) maven build faill silently and are not indicated by the script
(iv) extraction framework not compiling fully, maven could not download the `owlapi` dependency for the extraction live module

So after compiling everything I could manually and re-running the script, it finally got going. However,
after 1 hour or so, I got the following error:

```
PigLatin:DBpedia Spotlight: Names and entities for en got an error while submitting 
java.io.FileNotFoundException: File does not exist: /user/hadoop/en/sf_lookup/surfaceForms#sfs
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1128)
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1120)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1120)
        at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:288)
        at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:224)
        at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestamps(ClientDistributedCacheManager.java:99)
        at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities(ClientDistributedCacheManager.java:57)
        at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:265)
        at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:301)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:389)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
        at org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob.submit(ControlledJob.java:335)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.pig.backend.hadoop23.PigJobControl.submit(PigJobControl.java:128)
        at org.apache.pig.backend.hadoop23.PigJobControl.run(PigJobControl.java:191)
        at java.lang.Thread.run(Thread.java:745)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher$1.run(MapReduceLauncher.java:271```

**Comment by tgalery** [comment]
The pig script goes on and prints this other error:
```
2015-01-30 11:08:45,211 [main] ERROR org.apache.pig.tools.pigstats.SimplePigStats - ERROR: org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException: Application with id 'application_1422542657398_0004' doesn't exist in RM.
        at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getApplicationReport(ClientRMService.java:284)
        at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getApplicationReport(ApplicationClientProtocolPBServiceImpl.java:145)
        at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:321)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:599)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)```

**Comment by tgalery** [comment]
The main reasons for that seem to come from 

```macro_read_macro_redirectTransClo_macro_red_r1a_0_0_0,macro_read_parsedNonRedirects_0,macro_read_parsedRedirects_0,macro_read_parsed_0,ngramCounts,pageNgrams      MULTI_QUERY,COMBINER    Message: java.io.FileNotFoundException: File does not exist: /user/hadoop/en/sf_lookup/surfaceForms#sfs```

and

```Input(s):
Failed to read data from "/user/hadoop/enwiki-latest-pages-articles.xml"

Output(s):

Counters:
Total records written : 0
Total bytes written : 0
Spillable Memory Manager spill count : 0
Total bags proactively spilled: 0
Total records proactively spilled: 0

Job DAG:
job_1422542657398_0004  ->      null,
null    ->      null,
null    ->      null,
null    ->      null,
null    ->      null,
null    ->      null,
null    ->      null,
null
```

**Comment by tgalery** [comment]
Does this mean that the wikipedia upload to hdfs went wrong ?

**Comment by tgalery** [comment]
Hi @michellemay sorry to bother you with this, but I'm trying to generate a new model. I'm using your branches and everything compiles, but after a while I get this 
`2015-02-03 20:11:09,945 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 0% complete`
it seems to get stuck there. Have you experienced something similar. I'm using a cluster of 5 m3 larges (1 master +4 core nodes)

**Comment by neufang** [comment]
I have the same error.
My hadoop version is  2.6.0-cdh5.4.2.  Pig version 0.12.0 - cdh5.4.2.
Whats the file /sf_lookup/surfaceForms#sfs ?
How is it created?

2015-08-13 11:08:43,589 [JobControl] INFO  org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob - PigLatin:DBpedia Spotlight: Names and entities for nl got an error while submitting 
java.io.FileNotFoundException: File does not exist: /user/fxu/nl/sf_lookup/surfaceForms#sfs
	at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1132)
	at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1124)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1124)
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:288)
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:224)
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestamps(ClientDistributedCacheManager.java:99)
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities(ClientDistributedCacheManager.java:57)
	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:269)
	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:390)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:483)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1306)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1303)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1303)
	at org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob.submit(ControlledJob.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.pig.backend.hadoop23.PigJobControl.submit(PigJobControl.java:128)
	at org.apache.pig.backend.hadoop23.PigJobControl.run(PigJobControl.java:191)
	at java.lang.Thread.run(Thread.java:745)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher$1.run(MapReduceLauncher.java:270)

**Comment by gingaz** [comment]
Hi,

have you managed to solve the problem (tgalery commented on Jan 30) that causes 
Failed to read data from "/user/hadoop/enwiki-latest-pages-articles.xml"?

This does not seem like a permission issue. I can manipulate the file with the same user.

Cheers,
Gin

**Comment by tgalery** [comment]
@neufang @gingaz you should take a look at the .sh scripts that are executed. I remember that the file not found exception might be due to the fact that something might have changed at the haddop api level (I think 1.x uses `hadoop fs put` whilst newer versions uses `hdsfs put` or something like that). 
I really recommend trying to run this locally first, before you go on EMR. I think there are some german guys who made this work, you should take a look at PRs and Issues here and also at the `pirgnlproc` repo. Let me know how it goes.

**Comment by gingaz** [comment]
@tgalery thanks. Finally after playing with hadoop dependencies and tuning Yarn settings the cluster *seems* to work.  Don't have much results to share yet. If it works, I will outline the steps taken.

How long should it take for the "names and entities" script to complete on a full enwiki-latest-pages-articles.xml (52G)? What is the expected number of applications generated by the script?

I've got 2 tasks running at a time, currently processing application number 8. So far the script has been running for approx 16 hours and will run for at least another 48 hours. My cluster has only one node with 4 cores and 29 GB RAM.

**Comment by tgalery** [comment]
Yeah I dunno, last time I ran it, it took around 26 hours for me and it
threw a NPE, so my problem wasn't ram related. The clusters were much
bigger though (4 x 30 Gigs and 15GB master node). Not sure if yours will
do. Can you paste the steps and the modifications in the yml you did here ?

**Comment by gingaz** [comment]
yml?

Results running the scripts on standalone hadoop:
1. Script 'names_and_entities' finished successfully although with a few failed map jobs. The reason for the failed map jobs: timeouts connecting to hdfs cluster. Possibly memory configuration issues.
2. Script 'token_counts' fails with the output: http://pastebin.com/KQHZpM3E and http://pastebin.com/0BAT4vAD - no more details.
Running locally the 'token_counts' script runs out of memory. Apparently 26GB is not enough for the script.

Ok, so I in order to use hadoop 2.X I have built pignlproc (head revision) using org.apache.hadoop:hadoop-client:2.7.1 instead of the hadoop-core dependency and used the locally built spotlight version (head revision). Of course Pig 10.1 was built with "-Dhadoopversion=23"

Any ideas regarding the issues with "token_counts"?

Is dbpedia spotlight still relevant these days?
