### ISSUE TITLE
Difference in result while using JAVA API and on http://dbpedia-spotlight.github.io/demo/

### ISSUE THREAD

**Issue by riturajsingh-infotech** [dbpedia-spotlight/dbpedia-spotlight#350]
The code what I am using is:-
```
package extractKeyword;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.methods.GetMethod;
import org.dbpedia.spotlight.exceptions.AnnotationException;
import org.dbpedia.spotlight.model.DBpediaResource;
import org.dbpedia.spotlight.model.Text;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.LinkedList;
import java.util.List;

public class db extends AnnotationClient {

    //private final static String API_URL = "http://jodaiber.dyndns.org:2222/";
    private static String  API_URL    = "http://spotlight.dbpedia.org/";
    private static  double  CONFIDENCE = 0.0;
   private static  int     SUPPORT    = 0;
   // private static  String  powered_by ="non";
   // private static  String  spotter ="CoOccurrenceBasedSelector";//"LingPipeSpotter"=Annotate all spots 
                                                //AtLeastOneNounSelector"=No verbs and adjs.    
                                                //"CoOccurrenceBasedSelector" =No 'common words'
                                                //"NESpotter"=Only Per.,Org.,Loc.
    //private static String  disambiguator ="Default";//Default ;Occurrences=Occurrence-centric;Document=Document-centric
    //private static String  showScores ="yes";

@SuppressWarnings("static-access")
public void configiration(double CONFIDENCE,int SUPPORT)
//, String powered_by,String spotter,String disambiguator,String showScores)
{
    this.CONFIDENCE=CONFIDENCE;
    this.SUPPORT=SUPPORT;
   // this.powered_by=powered_by;
    //this.spotter=spotter;
    //this.disambiguator=disambiguator;
    //showScores=showScores;

}
    public List<DBpediaResource> extract(Text text) throws AnnotationException {
       // LOG.info("Querying API.");
        String spotlightResponse;
        try {
            String Query=API_URL + "rest/annotate/?" +
                    "confidence=" + CONFIDENCE
                 + "&support=" + SUPPORT
                 // + "&spotter=" + spotter
                 // + "&disambiguator=" + disambiguator
                 // + "&showScores=" + showScores
                 // + "&powered_by=" + powered_by
                  + "&text=" + URLEncoder.encode(text.text(), "utf-8");
            //LOG.info(Query);

            GetMethod getMethod = new GetMethod(Query);
            getMethod.addRequestHeader(new Header("Accept", "application/json"));
            spotlightResponse = request(getMethod);

        } catch (UnsupportedEncodingException e) {
            throw new AnnotationException("Could not encode text.", e);
        }
        assert     spotlightResponse != null;
        JSONObject resultJSON         = null;
        JSONArray  entities           = null;

        try {                   
            resultJSON = new JSONObject(spotlightResponse);
            entities = resultJSON.getJSONArray("Resources");

        } catch (JSONException e) {
            //throw new AnnotationException("Received invalid response from DBpedia Spotlight API.");
        }

        LinkedList<DBpediaResource> resources = new LinkedList<DBpediaResource>();
        if(entities!=null) 
        for(int i = 0; i < entities.length(); i++) {
            try {
                JSONObject entity = entities.getJSONObject(i);
                resources.add(
                        new DBpediaResource(entity.getString("@URI"),
                        Integer.parseInt(entity.getString("@support"))));
            } catch (JSONException e) {
                //((Object) LOG).error("JSON exception "+e);
            }
        }
        return resources;
    }

}
```

SECOND CLASS:-

```
package extractKeyword;
import org.apache.commons.httpclient.DefaultHttpMethodRetryHandler;
import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpException;
import org.apache.commons.httpclient.HttpMethodBase;
import org.apache.commons.httpclient.HttpStatus;
import org.apache.commons.httpclient.methods.GetMethod;
import org.apache.commons.httpclient.params.HttpMethodParams;
import org.dbpedia.spotlight.exceptions.AnnotationException;
import org.dbpedia.spotlight.model.DBpediaResource;
import org.dbpedia.spotlight.model.Text;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;

import javax.ws.rs.HttpMethod;

/**
 * @author pablomendes
 */
public abstract class AnnotationClient {

    //public Logger LOG = Logger.getLogger(this.getClass());
    private List<String> RES = new ArrayList<String>();

    // Create an instance of HttpClient.
    private static HttpClient client = new HttpClient();
    public List<String> getResu(){
        return RES;     
    }

    public String request(GetMethod getMethod) throws AnnotationException {
        String response = null;
        // Provide custom retry handler is necessary
        ( getMethod).getParams().setParameter(HttpMethodParams.RETRY_HANDLER,
                new DefaultHttpMethodRetryHandler(3, false));
        try {
            // Execute the method.
            int statusCode = client.executeMethod((org.apache.commons.httpclient.HttpMethod) getMethod);
            if (statusCode != HttpStatus.SC_OK) {
               // LOG.error("Method failed: " + ((HttpMethodBase) method).getStatusLine());
            }

            // Read the response body.
            byte[] responseBody = ((HttpMethodBase) getMethod).getResponseBody(); //TODO Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.

            // Deal with the response.
            // Use caution: ensure correct character encoding and is not binary data
            response = new String(responseBody);

        } catch (HttpException e) {
           // LOG.error("Fatal protocol violation: " + e.getMessage());
            throw new AnnotationException("Protocol error executing HTTP request.",e);
        } catch (IOException e) {
            //((Object) LOG).error("Fatal transport error: " + e.getMessage());
            //((Object) LOG).error(((HttpMethodBase) method).getQueryString());
            throw new AnnotationException("Transport error executing HTTP request.",e);
        } finally {
            // Release the connection.
            ((HttpMethodBase) getMethod).releaseConnection();
        }
        return response;

    }

    protected static String readFileAsString(String filePath) throws java.io.IOException{
        return readFileAsString(new File(filePath));
    }

    protected static String readFileAsString(File file) throws IOException {
        byte[] buffer = new byte[(int) file.length()];
        @SuppressWarnings("resource")
        BufferedInputStream f = new BufferedInputStream(new FileInputStream(file));
        f.read(buffer);
        return new String(buffer);
    }

    static abstract class LineParser {

        public abstract String parse(String s) throws ParseException;

        static class ManualDatasetLineParser extends LineParser {
            public String parse(String s) throws ParseException {
                return s.trim();
            }
        }

        static class OccTSVLineParser extends LineParser {
            public String parse(String s) throws ParseException {
                String result = s;
                try {
                    result = s.trim().split("\t")[3];
                } catch (ArrayIndexOutOfBoundsException e) {
                    throw new ParseException(e.getMessage(), 3);
                }
                return result; 
            }
        }
    }

    public void saveExtractedEntitiesSet(String Question, LineParser parser, int restartFrom) throws Exception {
        String text = Question;
        int i=0;
        //int correct =0 ; int error = 0;int sum = 0;

        for (String snippet: text.split("\n")) {
            String s = parser.parse(snippet);
            if (s!= null && !s.equals("")) {
                i++;

                if (i<restartFrom) continue;

                List<DBpediaResource> entities = new ArrayList<DBpediaResource>();

                try {
                    entities = extract(new Text(snippet.replaceAll("\\s+"," ")));
                    System.out.println(entities.get(0).getFullUri());

                } catch (AnnotationException e) {
                   // error++;
                    //LOG.error(e);
                    e.printStackTrace();
                }
                for (DBpediaResource e: entities) {
                    RES.add(e.uri());
                }
            }
        }
    }


    public abstract List<DBpediaResource> extract(Text text) throws AnnotationException;

    public void evaluate(String Question) throws Exception {
        evaluateManual(Question,0);
    }

    public void evaluateManual(String Question, int restartFrom) throws Exception {
         saveExtractedEntitiesSet(Question,new LineParser.ManualDatasetLineParser(), restartFrom);
    }
}
```
MAIN CLASS:-
```
package extractKeyword;

public class startAnnonation {
	public static void main(String[] args) throws Exception {
	    String question = "What is the winning chances of BJP in New Delhi elections?";
	    db c = new db ();
	    c.configiration(0.35,0);
	    //, 0, "non", "AtLeastOneNounSelector", "Default", "yes");
	    c.evaluate(question);
	    System.out.println("resource : "+c.getResu());
	}
}
```
The problem is when I am running the above code it gives the output But the result is different from the spotlight endpoint(http://dbpedia-spotlight.github.io/demo/). when I increase the confidence level the it gives error(Index Out of Bound exception).  IS there way to overcome this inconsistency in results?

**Comment by jodaiber** [comment]
Your code queries the endpoint `http://spotlight.dbpedia.org/ ` while the demo runs on the endpoint `http://spotlight.sztaki.hu:2222/rest`. That should explain the difference.

We should change that but I don't have access to `spotlight.dbpedia.org`. I assume @pablomendes does.

**Comment by riturajsingh-infotech** [comment]
When I changed my end ppint of query to 
```
private static String  API_URL    = "http://spotlight.sztaki.hu:2222/rest";
```
in my code. I got the error message as:-
```
Mar 18, 2015 3:58:50 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection timed out: connect
Mar 18, 2015 3:58:50 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Mar 18, 2015 3:59:11 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection timed out: connect
Mar 18, 2015 3:59:11 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Mar 18, 2015 3:59:32 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection timed out: connect
Mar 18, 2015 3:59:32 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
org.dbpedia.spotlight.exceptions.AnnotationException: Transport error executing HTTP request.
resource : []
	at extractKeyword.AnnotationClient.request(AnnotationClient.java:70)
	at extractKeyword.db.extract(db.java:62)
	at extractKeyword.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:129)
	at extractKeyword.AnnotationClient.evaluateManual(AnnotationClient.java:152)
	at extractKeyword.AnnotationClient.evaluate(AnnotationClient.java:148)
	at extractKeyword.startAnnonation.main(startAnnonation.java:9)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at extractKeyword.AnnotationClient.request(AnnotationClient.java:52)
	... 5 more

```
 Please correct me. What should I do for getting the same result as on http://dbpedia-spotlight.github.io/demo/(EndPoint:- http://spotlight.sztaki.hu:2222/rest).
@pablomendes  Please help me and @jodaiber please guide me through this.

**Comment by dav009** [comment]
@riturajsingh-infotech Given the previous code snippet you pasted  `API_URL` should be
`API_URL = http://spotlight.sztaki.hu:2222/` and not `http://spotlight.sztaki.hu:2222/rest`

**Comment by riturajsingh-infotech** [comment]
@jodaiber Sir, I tried it also as
```    
private static String  API_URL    = "http://spotlight.sztaki.hu:2222/";
```
But The result is same as
```
Mar 18, 2015 4:24:24 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection timed out: connect
Mar 18, 2015 4:24:24 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
```

**Comment by dav009** [comment]
can you please print the `url` which is being hit and the `request` which is being made when you call `extract`?

**Comment by riturajsingh-infotech** [comment]
```
   private static String  API_URL    = "http://spotlight.sztaki.hu:2222/";
    private static  double  CONFIDENCE = 0.0;
   private static  int     SUPPORT    = 0;
 public List<DBpediaResource> extract(Text text) throws AnnotationException {
       // LOG.info("Querying API.");
        String spotlightResponse;
        try {
            String Query=API_URL + "rest/annotate/?" +
                    "confidence=" + CONFIDENCE
                 + "&support=" + SUPPORT
                  + "&text=" + URLEncoder.encode(text.text(), "utf-8");
            //LOG.info(Query);

            GetMethod getMethod = new GetMethod(Query);
            getMethod.addRequestHeader(new Header("Accept", "application/json"));
            spotlightResponse = request(getMethod);

        } catch (UnsupportedEncodingException e) {
            throw new AnnotationException("Could not encode text.", e);
        }
        assert     spotlightResponse != null;
        JSONObject resultJSON         = null;
        JSONArray  entities           = null;

        try {                   
            resultJSON = new JSONObject(spotlightResponse);
            entities = resultJSON.getJSONArray("Resources");

        } catch (JSONException e) {
            //throw new AnnotationException("Received invalid response from DBpedia Spotlight API.");
        }

        LinkedList<DBpediaResource> resources = new LinkedList<DBpediaResource>();
        if(entities!=null) 
        for(int i = 0; i < entities.length(); i++) {
            try {
                JSONObject entity = entities.getJSONObject(i);
                resources.add(
                        new DBpediaResource(entity.getString("@URI"),
                        Integer.parseInt(entity.getString("@support"))));
            } catch (JSONException e) {
                //((Object) LOG).error("JSON exception "+e);
            }
        }
        return resources;
    }
```
I have also tried by changing String Query as  
```
 String Query=API_URL + 
                    "confidence=" + CONFIDENCE
                 + "&support=" + SUPPORT
                  + "&text=" + URLEncoder.encode(text.text(), "utf-8");
```

**Comment by dav009** [comment]
`Connection timed out: connect`, can you curl the endpoint? 
I would like to see the url which is actually hitting the endpoint without having to run your code.
So if you could paste it , it would be amazing

**Comment by riturajsingh-infotech** [comment]
@jodaiber 
http://spotlight.sztaki.hu:2222/annotate/?confidence=0.0&support=0&text=What+is+the+winning+chances+of+BJP+in+New+Delhi+elections%3F

**Comment by jodaiber** [comment]
The URL is

    http://spotlight.sztaki.hu:2222/rest/annotate/?confidence=0.35&support=0&text=What+is+the+winning+chances+of+BJP+in+New+Delhi+elections%3F

**Comment by riturajsingh-infotech** [comment]
@jodaiber 
Thanx a lot..a great help from your side.Now I am getting correct result as on spotlight demo.Once again Thank you for the great help.
