### ISSUE TITLE
Issues running statistical version using JAR

### ISSUE THREAD

**Issue by alegrm** [dbpedia-spotlight/dbpedia-spotlight#375]
Hi, 
I'm trying to set up the statistical version locally using the jar and the model:

```
    http://spotlight.sztaki.hu/downloads/version-0.1/en.tar.gz
    http://spotlight.sztaki.hu/downloads/version-0.1/dbpedia-spotlight.jar
```

when I uncompress the model file, seems It is corrupted:

```
    gzip: stdin: invalid compressed data--format violated
    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
```

do you have a checksum of the file?

Otherwise I tried to run dbpedia-spotlight-0.7.jar with http://spotlight.sztaki.hu/downloads/en_2+2.tar.gz, but I get an exception:

```
    INFO 2015-09-18 15:43:05,643 main [MemoryStore$] - Loading MemoryContextStore...
    Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
        at com.esotericsoftware.kryo.io.Input.require(Input.java:162)
        at com.esotericsoftware.kryo.io.Input.readInt(Input.java:296)
        at org.dbpedia.spotlight.db.memory.MemoryContextStore.read(MemoryContextStore.scala:127)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:363)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:355)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:157)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.loadContextStore(MemoryStore.scala:186)
        at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:57)
        at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
        at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
        at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:297)
        at org.dbpedia.spotlight.web.rest.Server.main(Server.java:98)
```

Thanks in advance for the help! :smile_cat:

**Comment by dav009** [comment]
Hi,

Best is to run 0.7.
with this jar: http://spotlight.sztaki.hu/downloads/dbpedia-spotlight-0.7.jar
and this model: http://spotlight.sztaki.hu/downloads/en_2+2.tar.gz

Could you please paste the command you used to try to get spotlight0.7  running?

**Comment by alegrm** [comment]
Hi, it is exactly this:

		$ java -jar dbpedia-spotlight-0.7.jar en_2+2 http://localhost:2222/rest
		 INFO 2015-09-18 17:36:36,727 main [MemoryStore$] - Loading MemoryQuantizedCountStore...
		 INFO 2015-09-18 17:36:36,751 main [MemoryStore$] - Done (24 ms)
		 INFO 2015-09-18 17:36:36,751 main [MemoryStore$] - Loading MemoryTokenTypeStore...
		 INFO 2015-09-18 17:36:37,131 main [MemoryTokenTypeStore] - Creating reverse-lookup for Tokens.
		 INFO 2015-09-18 17:36:37,435 main [MemoryStore$] - Done (684 ms)
		 INFO 2015-09-18 17:36:37,435 main [MemoryStore$] - Loading MemorySurfaceFormStore...
		 INFO 2015-09-18 17:36:49,649 main [MemorySurfaceFormStore] - Summing total SF counts.
		 INFO 2015-09-18 17:36:53,592 main [MemorySurfaceFormStore] - Creating reverse-lookup for surface forms, adding normalized surface forms.
		 INFO 2015-09-18 17:36:54,425 main [MemoryStore$] - Done (16990 ms)
		 INFO 2015-09-18 17:36:54,425 main [MemoryStore$] - Loading MemoryResourceStore...
		 INFO 2015-09-18 17:37:05,472 main [MemoryResourceStore] - Creating reverse-lookup for DBpedia resources.
		 INFO 2015-09-18 17:37:12,825 main [MemoryResourceStore] - Counting total support...
		 INFO 2015-09-18 17:37:18,607 main [MemoryResourceStore] - Done.
		 INFO 2015-09-18 17:37:18,607 main [MemoryStore$] - Done (24182 ms)
		 INFO 2015-09-18 17:37:18,608 main [MemoryStore$] - Loading MemoryCandidateMapStore...
		 INFO 2015-09-18 17:37:28,256 main [MemoryStore$] - Done (9648 ms)
		 INFO 2015-09-18 17:37:28,257 main [MemoryStore$] - Loading MemoryContextStore...
		Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
			at com.esotericsoftware.kryo.io.Input.require(Input.java:162)
			at com.esotericsoftware.kryo.io.Input.readInt(Input.java:296)
			at org.dbpedia.spotlight.db.memory.MemoryContextStore.read(MemoryContextStore.scala:127)
			at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:363)
			at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:355)
			at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
			at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:157)
			at org.dbpedia.spotlight.db.memory.MemoryStore$.loadContextStore(MemoryStore.scala:186)
			at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:57)
			at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
			at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
			at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:297)
			at org.dbpedia.spotlight.web.rest.Server.main(Server.java:98)

**Comment by dav009** [comment]
mm can you check your java version: `java -version`

I don't think this is the issue here but also be aware you should pass -Xmx9G -Xms9G or sim values to give it enough memory to run: i.e: `java  -Xmx9G -Xms9G java.jar ...`

**Comment by alegrm** [comment]
I have java 1.8. I also thought that may be a memory issue but the server has 15G available. I tried with the mx and ms parameters, but got the same error. I may try in another server on Monday...
