### ISSUE TITLE
dbpedia-spotlight demo web services is down

### ISSUE THREAD

**Issue by rub3nlh** [dbpedia-spotlight/dbpedia-spotlight#376]
Hello,
I was using your webservice and yesterday it stopped working. I also went to your test page http://dbpedia-spotlight.github.io/demo/ and it doesn't annotate even your default example...

Could anyone tell me if this is a permanent stop to this service or just a temporary failure?

Thank you

**Comment by jgrivolla** [comment]
The demo service fails quite regularly. You will need to set up your own instance (which is not very hard but needs quite a bit of RAM) if you want to use it in production (or even for reliable testing and development).

Notifications about this are sent to dbp-spotlight-developers@lists.sourceforge.net and you can subscribe at https://lists.sourceforge.net/lists/listinfo/dbp-spotlight-developers

According to the messages on the list the service goes up and down pretty much every day, and e.g. you can see that it went down on 09/30/2015 05:34:57AM and back up on 10/01/2015 05:34:57AM.

**Comment by rub3nlh** [comment]
Hi @jgrivolla thanks for your reply, 

I'm trying to install a local copy of spotligth from the "debian installation" ( https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Debian-Package-Installation:-How-To ) 
I set my server  up  to 15Gb Ram, and follow each step but doesnt work.

I'm having this error: 

Exception in thread "main" com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 12
 at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:113)
 at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:613)
 at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:724)
 at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:139)
 at org.dbpedia.spotlight.db.memory.MemoryStore$.loadSurfaceFormStore(MemoryStore.scala:152)
 at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:49)
 at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:62)
 at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
 at org.dbpedia.spotlight.web.rest.Server.main(Server.java:126)

 cat /var/log/dbpedia-spotlight-es.log
 
 
 org.dbpedia.spotlight.db.memory.MemoryStore$ load 
INFORMACIÓN: Loading MemoryTokenTypeStore...

 org.dbpedia.spotlight.db.memory.MemoryTokenTypeStore createReverseLookup
INFORMACIÓN: Creating reverse-lookup for Tokens.
org.dbpedia.spotlight.db.memory.MemoryStore$ load
INFORMACIÓN: Done (785 ms)
org.dbpedia.spotlight.db.memory.MemoryStore$ load
INFORMACIÓN: Loading MemorySurfaceFormStore...
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 12
 at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:113)
 at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:613)
 at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:724)
 at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:139)
 at org.dbpedia.spotlight.db.memory.MemoryStore$.loadSurfaceFormStore(MemoryStore.scala:152)
 at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:49)
 at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:62)
 at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
 at org.dbpedia.spotlight.web.rest.Server.main(Server.java:126)

-----
I found a similar error (april / 2014)
http://comments.gmane.org/gmane.comp.web.semantic.dbpedia-spotlight/601

Any comment will be very helpful,

**Comment by sandroacoelho** [comment]
Hi @rub3nlh 

You can run your own instance via [Docker]  (https://github.com/dbpedia-spotlight/spotlight-docker) . Our Debian packages are outdated and not supported yet (until we re-organize our release life cycle).

If you have some issue related,  just reopen this issue.

Thanks
