### ISSUE TITLE
Problems building a new spotlight index

### ISSUE THREAD

**Issue by arunbg** [dbpedia-spotlight/dbpedia-spotlight#378]
Hi,

I am trying to build a new spotlight model for English to make use of information in more recent DBpedia dumps. I ran into problems running on a Hadoop cluster, so to debug I thought of creating a smaller model (Italian) locally. I am also not using any OpenNLP stuff.

This is the command that I am running to build the model in 'local mode'.
`nohup ./index_db.sh -l wdir it_IT it/stopwords.list Italian models/it &`

I fixed a few broken URLs and some other issues, and have finally got it running until the Pig script without errors.
Running Pig gives me the following error in the stack trace.

```
Failed to parse: <file examples/indexing/names_and_entities.pig, line 43> 
Macro inline failed for macro 'read'. Reason: Macro contains argument or return value
MIN_SURFACE_FORM_LENGTH which conflicts with a Pig parameter of the same name.
```
[Full stack trace](https://gist.github.com/arunbg/e0f9ba014f9f32d8cfa1)

The same error was pointed out a while ago in an open issue https://github.com/dbpedia-spotlight/dbpedia-spotlight/issues/321

Has anyone managed to fix this error? Is there a better way build a new model?

**Comment by jodaiber** [comment]
Hey @arunbg,

I think that's pig-version related. Your log looks like you use 0.12 but index_db.sh should get 0.10, no?

Jo

**Comment by arunbg** [comment]
Thanks @jodaiber 
That particular error is now gone with Pig 0.10. I'm hitting new errors now and will update this thread if I can't resolve them. 

Thanks again for the quick response.

**Comment by arunbg** [comment]
After some wrangling, I'm happy to report that I was able to train a spotlight model **locally** for Italian from scratch. 

I tried doing the same for the larger English model, but am now hitting the following issue when running the names_and_entities.pig script (as part of index_db.sh)  
```
2015-12-04 08:14:44,787 [pool-10-thread-1] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader - Current split being processed file:/dbpedia/model-quickstarter/wdir/en_EN/enwiki-latest-pages-articles.xml:2483027968+33554432
2015-12-04 08:14:44,787 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.MapTask - io.sort.mb = 100
2015-12-04 08:14:50,492 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.LocalJobRunner - Starting task: attempt_local1170680236_0008_m_000075_0
2015-12-04 08:14:50,508 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.Task -  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@376a595d
2015-12-04 08:14:50,508 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.MapTask - Processing split: Number of splits :1
Total Length = 33554432
Input split[0]:
   Length = 33554432
  Locations:

-----------------------

2015-12-04 08:14:50,511 [pool-10-thread-1] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader - Current split being processed file:/dbpedia/model-quickstarter/wdir/en_EN/enwiki-latest-pages-articles.xml:2516582400+33554432
2015-12-04 08:14:50,511 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.MapTask - io.sort.mb = 100
2015-12-04 08:14:56,644 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.LocalJobRunner - Starting task: attempt_local1170680236_0008_m_000076_0
2015-12-04 08:14:56,655 [Thread-307] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Job job_pigexec_0 killed
Exception in thread "Thread-309" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1474)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:263)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:187)
	at org.apache.hadoop.mapred.FileOutputCommitter.cleanupJob(FileOutputCommitter.java:94)
	at org.apache.hadoop.mapred.FileOutputCommitter.abortJob(FileOutputCommitter.java:112)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:425)
```
A few lines earlier, there was a heap space error which may have been the root cause? 
```
2015-12-04 08:07:04,651 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 2998: Unhandled internal error. Java heap space
Details at logfile: /dbpedia/model-quickstarter/wdir/pig/pignlproc/pig_1449200604041.log
2015-12-04 08:07:04,652 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.LocalJobRunner - Starting task: attempt_local1170680236_0008_m_000001_0
2015-12-04 08:07:04,666 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.Task -  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@28740f1
2015-12-04 08:07:04,667 [pool-10-thread-1] INFO  org.apache.hadoop.mapred.MapTask - Processing split: Number of splits :1
Total Length = 33554432
Input split[0]:
   Length = 33554432
  Locations:
```

I am running this on a pretty big ec2 box with 256G of memory. I've also changed pignlproc/examples/indexing/names_and_entities.pig as suggested in docs for heap space issues. [Commit](https://github.com/arunbg/pignlproc/commit/a92cbb4cb3698c543b69c8270a83df394a7fae00)
The machine was hardly using any memory when the heap space error happened. 

Has anyone here run into something similar? Should I try running all of this on an EMR cluster?

**Comment by jodaiber** [comment]
This should be resolved with the new indexing pipeline (please reopen for other issues). I am running everything on a 32GB machine, but having an SSD of ~100GB speeds up everything significantly.
