### ISSUE TITLE
Monthly model build issues

### ISSUE THREAD

**Issue by jodaiber** [dbpedia-spotlight/dbpedia-spotlight#394]
Issues that need to be addressed:

- [x] / is annotated
- [x] remove List_of_*
- [x] More types in instance_types.nt

**Comment by arunbg** [comment]
Hey @jodaiber ,

The latest model is giving the following error when running the spotlight server for English.

``` 
INFO 2016-02-01 05:08:30,865 main [MemoryStore$] - Loading MemoryResourceStore...
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Error during Java deserialization.
Serialization trace:
ontologyTypeStore (org.dbpedia.spotlight.db.memory.MemoryResourceStore)
    at com.esotericsoftware.kryo.serializers.JavaSerializer.read(JavaSerializer.java:42)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:651)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
    at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:157)
    at org.dbpedia.spotlight.db.memory.MemoryStore$.loadResourceStore(MemoryStore.scala:176)
    at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:54)
    at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
    at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
    at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:297)
    at org.dbpedia.spotlight.web.rest.Server.main(Server.java:98)
Caused by: java.lang.ClassNotFoundException: org.dbpedia.spotlight.model.WikidataType
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
........
```
Are you able to run the server at your end?

**Comment by jodaiber** [comment]
Hi @arunbg,

are you using *-latest.jar or the latest main repo? The server runs fine on my end, but there were some updates to the code.

Jo

**Comment by arunbg** [comment]
Ah sorry, missed that. Works perfectly well with the new jar and the issues listed above look fixed. Great work!
