### ISSUE TITLE
Docker image not working - Unable to access jarfile

### ISSUE THREAD

**Issue by zmarty** [dbpedia-spotlight/dbpedia-spotlight#395]
I tried to run the English DBPedia Spotlight docker image from: https://hub.docker.com/r/dbpedia/spotlight-english/

Here is the command that I ran:
```
docker run --name dbpedia-spotlight-english -p 127.0.0.1:8004:80 --restart=always -d dbpedia/spotlight-english spotlight.sh
```

Here is the output of the docker logs command:
```
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
Unable to access jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar
```

**Comment by zmarty** [comment]
Here is the latest build that I tried to use right now: https://hub.docker.com/r/dbpedia/spotlight-english/builds/bsuq9hjcdnvvvwsxc2f52ik/

**Comment by zmarty** [comment]
I found the problem.

Here is the snippet from the Dockerfile:

```
ENV RELEASE_SERVER    spotlight.sztaki.hu
ENV RELEASE_FILENAME  dbpedia-spotlight-latest.jar
...
curl -O "http://$RELEASE_SERVER/downloads/$RELEASE_FILENAME"
...
ADD spotlight.sh /bin/spotlight.sh
```

And here is the snippet from spotlight.sh:
```
java -Dfile.encoding=UTF-8 -Xms12G -Xmx16G -jar -jar /opt/spotlight/dbpedia-spotlight-0.7.jar /opt/spotlight/en_2+2  http://localhost:80/rest
```

Notice that spotlight.sh is trying to use /opt/spotlight/dbpedia-spotlight-0.7.jar, but Dockerfile downloads dbpedia-spotlight-latest.jar by default.

**Comment by zmarty** [comment]
Well, even if I fix the image is still does not run. Here's the error after fixing and running the image:

```
Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in /opt/spotlight/en_2+2/model/tokens.mem.
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:47)
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:45)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:44)
        at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
        at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
        at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:297)
        at org.dbpedia.spotlight.web.rest.Server.main(Server.java:98)
```

**Comment by jodaiber** [comment]
Hey @zmarty ,

the jar is supposed to be *-latest.jar and the model folder is supposed to be /opt/spotlight/en. Can you please fix this, @sandroacoelho?

Best,
Jo

**Comment by sandroacoelho** [comment]
Hi @zmarty, @jodaiber 

Thank you to report it. I've updated the Dockerfile and forgot the shell script. 

Dockhub is now recompiling all the images and it takes some hours. When is done, I comment out here.

**Comment by jodaiber** [comment]
@sandroacoelho It's still pointing to `/opt/spotlight/en_2+2`. Please test code before you push it to a top-level Spotlight repo.

**Comment by sandroacoelho** [comment]
@jodaiber  done.

**Comment by sandroacoelho** [comment]
@zmarty : the new image is available. Could you please check if it works for you?
