### ISSUE TITLE
trying to implement dbpedia spotlight core into Apache Storm

### ISSUE THREAD

**Issue by clanstyles** [dbpedia-spotlight/dbpedia-spotlight#409]
The error
```Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to org.dbpedia.spotlight.db.memory.MemoryStore``

I've imported the dbpedia module into an apache storm project I've created. In a bolt, I initialize the dbpedia core as it is in the rest api.

On branch tags/release-0.7 in the file
```rest/src/main/java/org.dbpedia.spotlight.web.rest/Server```

function
```private static void initByModel(String folder) throws InitializationException```

My code is as follows:
```
    public TestBolt(String folder) {
        File modelFolder = null;

        try {
            modelFolder = new File(folder);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        SpotlightModel db = SpotlightModel.fromFolder(modelFolder);
        _spotter = db.spotters().get(SpotterConfiguration.SpotterPolicy.Default);
    }
```

I'm not sure what to do. I'd be willing to pay somebody to help. I'd share all the code, but it's really large, including this dbpedia spotlight core.

**Comment by sandroacoelho** [comment]
Hi  @clanstyles ,

It seems that you are trying cast MemoryStore to String, but to be sure what is happening, could you please share your code with us?

**Comment by clanstyles** [comment]
Hey @sandroacoelho ,

This code will reproduce the error exactly.

```
import org.dbpedia.spotlight.db.SpotlightModel;
import org.dbpedia.spotlight.exceptions.SpottingException;
import org.dbpedia.spotlight.model.SpotterConfiguration;
import org.dbpedia.spotlight.model.SurfaceFormOccurrence;
import org.dbpedia.spotlight.model.Text;
import org.dbpedia.spotlight.spot.Spotter;

import java.io.File;
import java.util.List;

/**
 * Created by styles on 10/20/16.
 */
public class Main {
    static Spotter _spotter = null;

    public static void main(String[] args) throws SpottingException {
        File modelFolder = null;
        try {
            modelFolder = new File("/Data/models/en/");
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        SpotlightModel db = SpotlightModel.fromFolder(modelFolder);
        _spotter = db.spotters().get(SpotterConfiguration.SpotterPolicy.Default);

        List<SurfaceFormOccurrence> spots = _spotter.extract(new Text("The cow jumps over the moon"));

        for (SurfaceFormOccurrence spot : spots) {
            System.out.println(spot.toString());
        }
    }
}
```

I want to start by saying, I'm comfortable with a lot of programming languages, but Java isn't one. The package managers drive me nuts.

I created a test project, and in IntelliJ I've added the source from 0.7 to modules. From run the above code. Below this is the POM file that I used 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>testproject</groupId>
    <artifactId>testproject</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <scala.compiler.version>2.10.4</scala.compiler.version>
        <lucene.version>3.6.0</lucene.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.dbpedia.spotlight</groupId>
            <artifactId>core</artifactId>
            <version>0.7</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-compiler</artifactId>
            <version>${scala.compiler.version}</version>
            <scope>provided</scope>
            <!--
                License: Scala License
                http://www.scala-lang.org/node/146
            -->
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.compiler.version}</version>
            <!--
                License: Scala License
                http://www.scala-lang.org/node/146
            -->
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-misc</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-queries</artifactId>
            <version>${lucene.version}</version>
            <type>jar</type>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-phonetic</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>9.4.0.M1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.esotericsoftware.kryo/kryo -->
        <dependency>
            <groupId>com.esotericsoftware.kryo</groupId>
            <artifactId>kryo</artifactId>
            <version>2.24.0</version>
        </dependency>

    </dependencies>
</project>
```

**Comment by clanstyles** [comment]
I can make another project and link you too it but I was afraid the modules wouldn't link up so you'd have to go through it and remap everything again.

**Comment by dav009** [comment]
can you share the whole stack strace?

**Comment by clanstyles** [comment]
```
Connected to the target VM, address: '127.0.0.1:33807', transport: 'socket'
 INFO 2016-10-20 13:55:24,656 main [MemoryStore$] - Loading MemoryQuantizedCountStore...
 INFO 2016-10-20 13:55:24,818 main [MemoryStore$] - Done (162 ms)
 INFO 2016-10-20 13:55:24,819 main [MemoryStore$] - Loading MemoryTokenTypeStore...
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to org.dbpedia.spotlight.db.memory.MemoryStore
	at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:160)
	at org.dbpedia.spotlight.db.memory.MemoryStore$.loadTokenTypeStore(MemoryStore.scala:168)
	at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:52)
	at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at Main.main(Main.java:26)
```

**Comment by dav009** [comment]
I wonder if the dbpedia jar you are using matches the one used to serialize the model you are using.
you have your dbpedia-spotlight.jar in your libs folder?

**Comment by dav009** [comment]
ah it has to do with the scala version you are specifying in your pom.
If you have `latest-dbpedia-spotlight.jar` as your dependency (`lib` folder) then you can just sack it off your .pom project.

It worked for me in your given project sample

**Comment by dav009** [comment]
I'm by no means an expert on Apache Storm, but from my basic understanding of it, adding a potentially long process (spot entities) /very  memory hungry component (like spotlight)  sounds like a red flag.
If only because Spotlight will compete with Storm for heap, and will share the same GC space.

**Comment by clanstyles** [comment]
I wasn't sure if Storm and this would actually play nice. I wanted to test it out. This smaller sample still had the same bug.

What scala version should I be using? If I remove the version, throws a completely different error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/Seq
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
Disconnected from the target VM, address: '127.0.0.1:41735', transport: 'socket'
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>testproject</groupId>
    <artifactId>testproject</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <lucene.version>3.6.0</lucene.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.dbpedia.spotlight</groupId>
            <artifactId>core</artifactId>
            <version>0.7</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-compiler</artifactId>
            <scope>provided</scope>
            <!--
                License: Scala License
                http://www.scala-lang.org/node/146
            -->
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <!--
                License: Scala License
                http://www.scala-lang.org/node/146
            -->
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-misc</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-queries</artifactId>
            <version>${lucene.version}</version>
            <type>jar</type>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-phonetic</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>9.4.0.M1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.esotericsoftware.kryo/kryo -->
        <dependency>
            <groupId>com.esotericsoftware.kryo</groupId>
            <artifactId>kryo</artifactId>
            <version>2.24.0</version>
        </dependency>

    </dependencies>
</project>
```

**Comment by clanstyles** [comment]
My version of dbpedia is at ``` * tag               release-0.7.2 -> FETCH_HEAD```

I downloaded the models from http://spotlight.sztaki.hu/downloads/ I'm still confused what I'm doing wrong. Thank you @dav009 for your help so far.

**Comment by dav009** [comment]
you don't need to specify a scala version cause it comes as part of the packaged spotlight jar.
Just for the sake of checking your sample project, can you pick the jar from http://spotlight.sztaki.hu/downloads/dbpedia-spotlight-latest.jar

**Comment by clanstyles** [comment]
I'm still receiving the same error:
```Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to org.dbpedia.spotlight.db.memory.MemoryStore```

**Comment by dav009** [comment]
are you sure, that intelliJ  is using the spotlight jar in your lib folder, and not another one? i.e: maven, ivy, or somewhere else in your classpath

**Comment by clanstyles** [comment]
I'm not quite sure. I've gone into the project settings and set it up as the library. I cleaned it and rebuilt it.

![dbpedia libraries](https://cloud.githubusercontent.com/assets/643269/19574727/945e99ca-96d9-11e6-97d4-9e990864acda.png)

**Comment by dav009** [comment]
is this the toy project? there are 65 problems, check if spotlight is among them?

**Comment by clanstyles** [comment]
I do see that there is a whole section about Platform settings -> Global Libraries. This does say that the scala-sdk-2.10.4 is loaded. If you're saying that it's the Scala version, maybe the global library is overriding what dbpedia-spotlight-latest.jar wants?

**Comment by dav009** [comment]
yeah, remove it from global libs. also remove the dependency from your pom
