### ISSUE TITLE
Transport error executing HTTP request.

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#448]
Hello,

I tried to execute my code and i get the following error:

Fatal transport error: Connection refused: connect
org.dbpedia.spotlight.exceptions.AnnotationException: Transport error executing HTTP request.
	at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:73)
	at de.dwslab.petar.walks.DBpediaSpotlightClient.extract(DBpediaSpotlightClient.java:45)
	at de.dwslab.petar.walks.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:129)
	at de.dwslab.petar.walks.AnnotationClient.evaluateManual(AnnotationClient.java:160)
	at de.dwslab.petar.walks.AnnotationClient.evaluate(AnnotationClient.java:156)
	at de.dwslab.petar.walks.DBpediaSpotlightClient.main(DBpediaSpotlightClient.java:150)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:56)
	... 5 more

Which is a new error.  The API url  used is : "http://model.dbpedia-spotlight.org:2222/".

Can you please help my by identifying my error! and how i know the correct API_URL, because it seems that this url change over the time!
thank you

**Comment by sandroacoelho** [comment]
Hi,

Please try http://model.dbpedia-spotlight.org/en

**Comment by TamouzeAssi** [comment]
Hi @sandroacoelho 
I tried the given API and i get 
org.dbpedia.spotlight.exceptions.AnnotationException: Received invalid response from DBpedia Spotlight API.
...

**Comment by sandroacoelho** [comment]
Hey, 

It works for me http://model.dbpedia-spotlight.org/en/annotate/?text=Berlin%20is%20the%20capital%20of%20germany

**Comment by TamouzeAssi** [comment]
I will try again, may be my .jar is not working well. By the way can you please tell me which spotlight jar are you used.
for me im using dbpedia-spotlight-0.5.2-jar-with-dependencies.jar
Thank you

**Comment by sandroacoelho** [comment]
1.0.0 at http://downloads.dbpedia-spotlight.org/spotlight/

**Comment by TamouzeAssi** [comment]
Hello Sir @sandroacoelho ,
I did all your suggestions but still have the same problem.
We treat the line:
 Berlin is the capital of germany
org.dbpedia.spotlight.exceptions.AnnotationException: Received invalid response from DBpedia Spotlight API.
	at DBpediaSpotlightClient.extract(DBpediaSpotlightClient.java:68)
	at AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:190)
	at AnnotationClient.evaluateManual(AnnotationClient.java:224)
	at AnnotationClient.evaluate(AnnotationClient.java:220)
	at DBpediaSpotlightClient.main(DBpediaSpotlightClient.java:126)
Exception in thread "main" java.lang.NullPointerException
	at DBpediaSpotlightClient.replaceText(DBpediaSpotlightClient.java:94)
	at AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:203)
	at AnnotationClient.evaluateManual(AnnotationClient.java:224)
	at AnnotationClient.evaluate(AnnotationClient.java:220)
	at DBpediaSpotlightClient.main(DBpediaSpotlightClient.java:126)

the used class is:


import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.dbpedia.spotlight.exceptions.AnnotationException;
import org.dbpedia.spotlight.model.DBpediaResource;
import org.dbpedia.spotlight.model.Text;

import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.methods.GetMethod;
import org.dbpedia.spotlight.exceptions.AnnotationException;
import org.dbpedia.spotlight.model.DBpediaResource;
import org.dbpedia.spotlight.model.Text;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.LinkedList;
import java.util.List;

/**
 * Simple web service-based annotation client for DBpedia Spotlight.
 *
 * @author pablomendes, Joachim Daiber
 */

public class DBpediaSpotlightClient extends AnnotationClient {
	JSONArray  entities = null;
	//private final static String API_URL = "http://model.dbpedia-spotlight.org/en";
	//private static String  API_URL    = "http://spotlight.sztaki.hu:2222/rest";
	//private final static String API_URL = "http://spotlight.dbpedia.org/";
	private static String  API_URL    = "http://model.dbpedia-spotlight.org/en/annotate";
	private static final double CONFIDENCE = 0.1;
	private static final int SUPPORT = 0;
	
	public List<DBpediaResource> extract(Text text) throws AnnotationException {
		   // LOG.info("Querying API.");
		    String spotlightResponse;
			    //System.out.println("Text= "+text);
		    try {
		    	GetMethod getMethod = new GetMethod(API_URL + "rest/annotate/?" +
						"confidence=" + CONFIDENCE
						+ "&support=" + SUPPORT
						+ "&text=" + URLEncoder.encode(text.text(), "utf-8"));
				getMethod.addRequestHeader(new Header("Accept", "application/json"));
		        
		        spotlightResponse = request(getMethod);
		        
		        
		      
		    } catch (UnsupportedEncodingException e) {
		        throw new AnnotationException("Could not encode text.", e);
		    }
		    assert     spotlightResponse != null;
		    JSONObject resultJSON         = null;
		    entities           = null;

		    try {                   
		        resultJSON = new JSONObject(spotlightResponse);
		        
		        entities = resultJSON.getJSONArray("Resources");
		    } catch (JSONException e) {
		        throw new AnnotationException("Received invalid response from DBpedia Spotlight API.");
		    }

		    LinkedList<DBpediaResource> resources = new LinkedList<DBpediaResource>();
		    if(entities!=null) 
		    for(int i = 0; i < entities.length(); i++) {
		        try {
		            JSONObject entity = entities.getJSONObject(i);
		            
		            resources.add(
		                    new DBpediaResource(entity.getString("@URI"),
		                    Integer.parseInt(entity.getString("@support"))));
		           
		            
		        } catch (JSONException e) {
		            //LOG.error("JSON exception "+e);
		        }
		    }
		    
		    return resources;
		  }

	
	
		
		

		public JSONArray getEntities(){
			return entities;
		}
        public static void main(String[] args) throws Exception {


        DBpediaSpotlightClient c = new DBpediaSpotlightClient ();

        File input = new File("C:/Users/user/workspaceMars/LOD2Walks/output/outputPaths/anno.txt");
        File output = new File("C:/Users/user/workspaceMars/Spotlight/marsAnnotated.txt");
        c.evaluate(input, output);

        System.out.println("Done");

    }
}

Im sorry for disturbing but im working on a research project and still this error delaying me :( 

Can i get your advice?
Thank you

**Comment by sandroacoelho** [comment]
Hi @TamouzeAssi 

Please try [spotlight-example.zip](https://github.com/dbpedia-spotlight/dbpedia-spotlight/files/1203114/spotlight-example.zip)

Best,
