### ISSUE TITLE
Transport error executing HTTP request.

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#449]
Hello,

I tried to execute my code and i get the following error:

Fatal transport error: Connection refused: connect
org.dbpedia.spotlight.exceptions.AnnotationException: Transport error executing HTTP request.
	at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:73)
	at de.dwslab.petar.walks.DBpediaSpotlightClient.extract(DBpediaSpotlightClient.java:45)
	at de.dwslab.petar.walks.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:129)
	at de.dwslab.petar.walks.AnnotationClient.evaluateManual(AnnotationClient.java:160)
	at de.dwslab.petar.walks.AnnotationClient.evaluate(AnnotationClient.java:156)
	at de.dwslab.petar.walks.DBpediaSpotlightClient.main(DBpediaSpotlightClient.java:150)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:56)
	... 5 more

Which is a new error(for me).  The API url  used is : "http://model.dbpedia-spotlight.org:2222/".

Can you please help my by identifying my error! and how i know the correct API_URL, because it seems that this url change each time!
thank you

**Comment by sandroacoelho** [comment]
Duplicated issue #448
