### ISSUE TITLE
Annotate big file

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#451]
Hello,

Trying to annotatate a big file using the web service and after several hours the spotlight server stop responding due the overload request. So what is the best the way to annotate that file.

I think to build spotlight from source with Maven. But i cant find the files: disambiguation index and the spotter lexicon. The given link is broken.

So, do you think is the best way to annotate my file?

Thank you

**Comment by sandroacoelho** [comment]
Hi, 

Have you tried?
`
wget http://downloads.dbpedia-spotlight.org/spotlight/dbpedia-spotlight-1.0.0.jar
wget http://downloads.dbpedia-spotlight.org/2016-04/en/model/en.tar.gz
tar xzf en.tar.gz
java -jar dbpedia-spotlight-1.0.jar en http://localhost:2222/rest
`

**Comment by TamouzeAssi** [comment]
Hi @sandroacoelho ,

I tried it now and i get.

Firstly
Error: Unable to access jarfile dbpedia-spotlight-1.0.jar

so i tried to modify your last line as following:

$ java -jar dbpedia-spotlight-1.0.0.jar en http://localhost:2222/rest

and now i got the following:

Exception in thread "main" java.io.IOException: Invalid Spotlight model folder: Could not read required file tokens.mem in en/model/tokens.mem.
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:48)
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.apply(SpotlightModel.scala:46)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:45)
        at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80)
        at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
        at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:229)
        at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)


I have already prepare my own code as browsing my file then take a line form it and execute the annotation step by using the api-url:
private  String  API_URL    = "http://model.dbpedia-spotlight.org/en/annotate";

How can i install the dpedia spotlight and instead using the above API_URl, i use 

private  String  API_URL    = http://localhost:2222/rest"

Thank you

**Comment by sandroacoelho** [comment]
Weird. Seems that you have not downloaded and unpack the model files. Could you please try to download the English model again(wget http://downloads.dbpedia-spotlight.org/2016-04/en/model/en.tar.gz)?

**Comment by TamouzeAssi** [comment]
Still the same. Even i tried:

wget http://downloads.dbpedia-spotlight.org/spotlight/dbpedia-spotlight-1.0.0.jar

wget http://downloads.dbpedia-spotlight.org/2016-04/en/model/en.tar.gz

tar xzf en.tar.gz

java -jar dbpedia-spotlight-latest.jar en_2+2 http://localhost:2222/rest

and get the same error which is : 
Error: Unable to access jarfile dbpedia-spotlight-latest.jar

**Comment by TamouzeAssi** [comment]
@sandroacoelho 

May be i find the error:

when you unpack the model file, we get something like en_2+2.
So i juste rename it as en. 
and the type 
java -jar dbpedia-spotlight-1.0.jar en http://localhost:2222/rest.

So, after some loading, i get something like 

Server started in /gs/home/tamouze listening on http://localhost:2222/rest

but please how can i use that in my code.

**Comment by sandroacoelho** [comment]
oh.. Sorry about the broken links. I will fix it.

At your code, just replace http://model.dbpedia-spotlight.org/en to http://localhost:2222/rest
Eg: 

private String API_URL = http://localhost:2222/rest"?

**Comment by TamouzeAssi** [comment]
Hi @sandroacoelho ,

Thank you for you help.

I think we are talking about two differents program structures. 
Let me tell you what is my program structure.
Im using an SSH server, on that server i deploy my own maven project which has the following pom.xml :
 
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.dwslab.petar</groupId>
	<artifactId>Load2Walks</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.6.0</version>
        <configuration>
             <mainClass>org.spotlight.DbSpotlightClient</mainClass> 
             
        </configuration>
        </plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>fully.qualified.MainClass</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>

	</build>
	<dependencies>

		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j</artifactId>
			<version>3.0.0-M04</version>
		</dependency>
		 <dependency>
        <groupId>org.ahocorasick</groupId>
        <artifactId>ahocorasick</artifactId>
        <version>0.3.1</version>
    </dependency>
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>apache-jena-libs</artifactId>
			<type>pom</type>
			<version>2.13.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.6</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.1</version>
        </dependency>
         <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency>
          <dependency>
        **<groupId>org.spotlight</groupId>
        <artifactId>dbpedia-spotlight</artifactId>
        <version>1.0.0</version**>
 </dependency>
	</dependencies>
</project>`

To execute my project, I type in the command line (when im in my project folder):
1- mvn clean install
2- mvn exec:java

It is working fine. But my program call the remote web service.

So, I tried to modify as you told my api_ur. Now i typed : 

java -jar dbpedia-spotlight-1.0.jar en http://localhost:2222/rest.

which  start the server as you told without any error: i get the following:
```
[tamouze@lg-1r17-n04 tws-462-aa]$ java -jar dbpedia-spotlight-1.0.0.jar en http://localhost:2222/rest
276 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryQuantizedCountStore...
324 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (46 ms)
324 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryTokenTypeStore...
691 [main] INFO org.dbpedia.spotlight.db.memory.MemoryTokenTypeStore - Creating reverse-lookup for Tokens.
946 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (622 ms)
947 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemorySurfaceFormStore...
5182 [main] INFO org.dbpedia.spotlight.db.memory.MemorySurfaceFormStore - Summing total SF counts.
10689 [main] INFO org.dbpedia.spotlight.db.memory.MemorySurfaceFormStore - Creating reverse-lookup for surface forms, adding normalized surface forms.
11673 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (10725 ms)
11673 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryResourceStore...
13725 [main] INFO org.dbpedia.spotlight.db.memory.MemoryResourceStore - Creating reverse-lookup for DBpedia resources.
15037 [main] INFO org.dbpedia.spotlight.db.memory.MemoryResourceStore - Counting total support...
15294 [main] INFO org.dbpedia.spotlight.db.memory.MemoryResourceStore - Done.
15295 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (3622 ms)
15295 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryCandidateMapStore...
25550 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (10255 ms)
25551 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading MemoryContextStore...
35428 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (9877 ms)
39385 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Loading FSADictionary...
39890 [main] INFO org.dbpedia.spotlight.db.memory.MemoryStore$ - Done (505 ms)
40196 [main] INFO org.dbpedia.spotlight.web.rest.Server - Initiated 1 disambiguators.
40196 [main] INFO org.dbpedia.spotlight.web.rest.Server - Initiated 2 spotters.
Aug 30, 2017 11:27:39 AM com.sun.grizzly.Controller logVersion
INFO: GRIZZLY0001: Starting Grizzly Framework 1.9.48 - 8/30/17 11:27 AM
Server started in /gs/project/tws-462-aa listening on http://localhost:2222/rest
```
Now, i cant type anything in my command line, see please image 1
![image1](https://user-images.githubusercontent.com/16214827/29882602-8a8d233c-8d7b-11e7-874b-60e96b7eb8be.jpg)
.

So to can type something i just press CTR+C,  to get 

[tamouze@lg-1r17-n04 tws-462-aa]$

Now i modify the api_url as you told, 

type `mvn compile` then `mvn exec:java`,  i get the error shown in image 2
![image2](https://user-images.githubusercontent.com/16214827/29882783-24339598-8d7c-11e7-857a-44a83a00e688.jpg)

So, how can integrate the dbpedia-spotlight in my project without calling the remote-web service?

does I need to change my program structure, my development environement?

Regards

**Comment by sandroacoelho** [comment]
Got it!  Bash offers an option to start a program as a background job with  "nohup and &" on the command line. Just run ```nohup java -jar dbpedia-spotlight-1.0.jar en http://localhost:2222/rest & ```. 

The service will start at localhost:2222 and the terminal will be free to type new commands. 
E.g:

```curl http://localhost:2222/rest/annotate?text=Berlin is the capital of Germany ```

Best

**Comment by TamouzeAssi** [comment]
Sir @sandroacoelho ,

First of all, thank you for your patience, you help your advices. With your help, I can now curl the endpoint and comparing to curl the remote endpoint its look like more fast. But I have a question, please, what is the difference between the zipped-code you send me one time called "spotlight-example" and the old one available online?
Again, thank you so much

**Comment by TamouzeAssi** [comment]
Unfortunately, I remark after 12 h of execution we get the following exception. Does any relations between the zize of the data and the end-point execution. The execution was runing very well!
 
```
org.dbpedia.spotlight.exceptions.AnnotationException: Transport error executing HTTP request.
        at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:73)
        at de.dwslab.petar.walks.DBpediaSpotlightClient.extract(DBpediaSpotlightClient.java:46)
        at de.dwslab.petar.walks.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:129)
        at de.dwslab.petar.walks.AnnotationClient.evaluateManual(AnnotationClient.java:160)
        at de.dwslab.petar.walks.AnnotationClient.evaluate(AnnotationClient.java:156)
        at de.dwslab.petar.walks.DBpediaSpotlightClient.main(DBpediaSpotlightClient.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:286)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at de.dwslab.petar.walks.AnnotationClient.request(AnnotationClient.java:56)
        ... 11 more
done
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:52 h
[INFO] Finished at: 2017-08-31T14:20:13-04:00
[INFO] Final Memory: 11M/976M
[INFO] ------------------------------------------------------------------------
```

**Comment by TamouzeAssi** [comment]
Hi @sandroacoelho,

My file is around 2.290559 Gb. 

It looks like the web-service shutdown after sometimes!

**Comment by sandroacoelho** [comment]
mmmm 2.30 gb is too large for a REST interface. What about to slice it in small requests?

**Comment by TamouzeAssi** [comment]
In each iteration in code, i take one line from this file and try to annotate it.

**Comment by sandroacoelho** [comment]
How many requests are you sending per minute? Could you please limit it to ~ 60 requests / minute

**Comment by TamouzeAssi** [comment]
Sorry, but can i knwo that? And how can i limit the number of requests?
