### ISSUE TITLE
HTTP Error 502 - Bad Gateway during api call to spotlight

### ISSUE THREAD

**Issue by kavin26** [dbpedia-spotlight/dbpedia-spotlight#455]
I made an api call to dbpedia spotlight model (english) from python3.5,the code is given as 
`entities=entity_extraction(doc=raw_docs[i],req_params={'url':'http://model.dbpedia-spotlight.org/en/annotate','spotter':'Default','support':20,'confidence':0.8,'disambiguator':'Default'})` where `entity_extraction()` is a python function where i called the necessary `urllib methods` for placing the calls and getting the result. But when i connected to it yesterday for creating graph data, it gave me `connection timed out error` and today it gave me,
`Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<input>", line 114, in entity_extraction
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
`
what might be the reason for unable to access dbpedia spotlight api for entity extraction?

**Comment by sandroacoelho** [comment]
Hi @kavin26,

The service was down. Could you please try again?

Thanks,
